version: "3"
services:
  api:
    container_name: frontend-admin
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
